# Publishing derived from https://docs.pypi.org/trusted-publishers/
# Building derived from https://github.com/Farama-Foundation/Gymnasium/blob/main/.github/workflows/pypi-publish.yml

on:
  release:
    types:
      - published

name: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5

    - name: Install dependencies
      run: pipx install build

    - name: Build sdist and wheels
      run: pyproject-build

    - name: Store wheels
      uses: actions/upload-artifact@v4
      with:
        path: dist

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
